"use client";

import React, { useState } from "react";
import { Database, ShieldCheck, Copy, Check, AlertCircle, Info } from "lucide-react";
import { SqlExecutionInfo } from "@/types";

interface SqlViewerProps {
  sqlInfo?: SqlExecutionInfo;
}

export const SqlViewer: React.FC<SqlViewerProps> = ({ sqlInfo }) => {
  const [copied, setCopied] = useState(false);

  const hasSql = Boolean(sqlInfo?.available && sqlInfo?.sql);

  const handleCopy = () => {
    if (sqlInfo?.sql) {
      navigator.clipboard.writeText(sqlInfo.sql);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <div className="rounded-2xl bg-slate-950/80 border border-slate-800/80 p-4 space-y-3">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-slate-800/80 pb-2.5">
        <div className="flex items-center gap-2">
          <Database className="w-4 h-4 text-emerald-400" />
          <span className="text-xs font-bold text-slate-200 uppercase tracking-wider">
            Semantic Layer SQL Execution
          </span>
        </div>
        <div className="flex items-center gap-2 text-[11px] font-mono">
          <span className="text-slate-400">SQL SOURCE:</span>
          <span className="text-emerald-400 font-bold">
            {sqlInfo?.source || "Cube Semantic Layer"}
          </span>
        </div>
      </div>

      {/* Critical Transparency Notice */}
      <div className="p-3 rounded-xl bg-slate-900/60 border border-slate-800 space-y-1">
        <div className="flex items-center gap-2 text-xs font-semibold text-slate-200">
          <ShieldCheck className="w-4 h-4 text-emerald-400 shrink-0" />
          <span>SQL generated/executed by the semantic layer</span>
        </div>
        <div className="text-[11px] text-slate-400 pl-6">
          SQL generated by LLM: <strong className="text-emerald-400 font-mono">NONE</strong>.
          MetricMind uses semantic contracts to prevent SQL injection and hallucinated calculations.
        </div>
      </div>

      {/* SQL Content or Unavailable Disclaimer */}
      {hasSql ? (
        <div className="space-y-1.5">
          <div className="flex items-center justify-between">
            <span className="text-[10px] font-bold text-slate-400 uppercase">
              Physical Warehouse Query
            </span>
            <button
              onClick={handleCopy}
              className="flex items-center gap-1 text-[11px] text-slate-400 hover:text-emerald-300 transition-colors"
            >
              {copied ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
              <span>{copied ? "Copied" : "Copy SQL"}</span>
            </button>
          </div>
          <pre className="p-3 rounded-xl bg-black/70 border border-slate-800 text-emerald-300 font-mono text-[11px] overflow-x-auto max-h-56 leading-relaxed">
            {sqlInfo?.sql}
          </pre>
        </div>
      ) : (
        <div className="p-4 rounded-xl bg-slate-900/40 border border-slate-800 text-xs text-slate-300 flex items-start gap-2.5">
          <Info className="w-4 h-4 text-sky-400 shrink-0 mt-0.5" />
          <div className="space-y-1">
            <p className="font-medium text-slate-200">
              SQL preview is unavailable for this semantic query.
            </p>
            <p className="text-[11px] text-slate-400 leading-relaxed">
              The request was executed through the Cube Semantic Layer. MetricMind does not fabricate
              or invent hypothetical SQL strings when the execution engine delegates directly to the
              governed data warehouse adapter.
            </p>
          </div>
        </div>
      )}
    </div>
  );
};
