"use client";

import React from "react";
import Link from "next/link";
import { ArrowLeft, FileText, ShieldCheck } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto space-y-8">
        <div className="flex items-center justify-between border-b border-slate-800 pb-4">
          <Link
            href="/signup"
            className="inline-flex items-center gap-2 text-xs font-semibold text-sky-400 hover:text-sky-300 transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            <span>Back to Sign Up</span>
          </Link>
          <span className="text-xs font-mono text-slate-500">v1.0.0 Governed BI</span>
        </div>

        <div className="space-y-3">
          <div className="w-12 h-12 rounded-xl bg-sky-500/10 border border-sky-500/30 flex items-center justify-center text-sky-400">
            <FileText className="w-6 h-6" />
          </div>
          <h1 className="text-3xl font-bold tracking-tight text-slate-100">
            Terms of Service
          </h1>
          <p className="text-xs text-slate-400">
            Effective Date: January 1, 2026 • MetricMind Enterprise
          </p>
        </div>

        <div className="space-y-6 text-sm text-slate-300 leading-relaxed bg-slate-900/60 border border-slate-800 p-6 sm:p-8 rounded-2xl">
          <section className="space-y-2">
            <h2 className="text-base font-semibold text-slate-100">
              1. Authorized Corporate Intelligence Use
            </h2>
            <p className="text-slate-400 text-xs sm:text-sm">
              By accessing or creating an account on MetricMind, you agree to adhere to your organization&apos;s data governance policies. MetricMind is licensed exclusively for authorized business intelligence, executive reasoning, and governed metric consumption.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-semibold text-slate-100">
              2. Semantic Governance & Integrity
            </h2>
            <p className="text-slate-400 text-xs sm:text-sm">
              All metrics generated by the MetricMind Agentic Engine are verified against certified dbt and Cube semantic definitions. Direct execution of un-governed SQL against production data stores is prohibited and blocked by the governance gateway.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-semibold text-slate-100">
              3. Role-Based Permissions
            </h2>
            <p className="text-slate-400 text-xs sm:text-sm">
              User accounts are provisioned with specific organizational roles (Executive, Finance Analyst, Sales Analyst, Admin). Permissions to view sensitive financial data, export reports, or alter semantic definitions are determined strictly by backend role enforcement.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-semibold text-slate-100">
              4. Account Security
            </h2>
            <p className="text-slate-400 text-xs sm:text-sm">
              Users are responsible for safeguarding corporate account credentials and complying with enterprise password requirements (minimum 8 characters, multi-character complexity).
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
