-- ==============================================================================
-- METRICMIND — AGENTIC SEMANTIC BI ENGINE
-- Enterprise Seed Data (PostgreSQL)
-- ==============================================================================

-- 1. Insert Governed Metric Definitions
INSERT INTO metric_definitions (metric_name, display_name, description, formula_sql, allowed_dimensions, owner_team, version, is_active)
VALUES
(
    'revenue',
    'Gross Revenue',
    'Total recognized revenue across completed enterprise transactions prior to tax.',
    'SUM(quantity * unit_price * (1.0 - discount / 100.0))',
    ARRAY['order_date', 'region_name', 'country', 'continent', 'customer_name', 'customer_segment', 'product_name', 'category', 'subcategory'],
    'Strategic Finance',
    2,
    TRUE
),
(
    'cost',
    'Cost of Goods Sold (COGS)',
    'Direct software delivery, cloud infrastructure, hardware, and logistical fulfillment cost.',
    'SUM(quantity * unit_cost)',
    ARRAY['order_date', 'region_name', 'country', 'continent', 'customer_name', 'customer_segment', 'product_name', 'category', 'subcategory'],
    'Data Operations',
    2,
    TRUE
),
(
    'gross_profit',
    'Gross Profit',
    'Operating earnings generated by subtracting direct Cost of Goods Sold from Revenue.',
    'SUM(revenue) - SUM(cost)',
    ARRAY['order_date', 'region_name', 'country', 'continent', 'customer_name', 'customer_segment', 'product_name', 'category', 'subcategory'],
    'Strategic Finance',
    3,
    TRUE
),
(
    'margin',
    'Gross Margin %',
    'Percentage of top-line revenue retained after deducting COGS. Governed corporate formula: ((Revenue - Cost) / Revenue) * 100.',
    '((SUM(revenue) - SUM(cost)) * 1.0 / NULLIF(SUM(revenue), 0)) * 100.0',
    ARRAY['order_date', 'region_name', 'country', 'continent', 'customer_name', 'customer_segment', 'product_name', 'category', 'subcategory'],
    'Strategic Finance',
    3,
    TRUE
),
(
    'orders',
    'Total Order Volume',
    'Distinct count of successfully completed enterprise contracts and purchase orders.',
    'COUNT(DISTINCT order_id)',
    ARRAY['order_date', 'region_name', 'country', 'continent', 'customer_name', 'customer_segment', 'product_name', 'category'],
    'Sales Operations',
    1,
    TRUE
);

-- 2. Insert Regions
INSERT INTO regions (region_id, region_name, country, continent) VALUES
(1, 'Central Europe', 'Germany', 'Europe'),
(2, 'Western Europe', 'France', 'Europe'),
(3, 'Northern Europe', 'United Kingdom', 'Europe'),
(4, 'South Asia', 'India', 'Asia'),
(5, 'East Asia', 'Japan', 'Asia'),
(6, 'US East & West', 'United States', 'North America'),
(7, 'North America North', 'Canada', 'North America');

ALTER SEQUENCE regions_region_id_seq RESTART WITH 8;

-- 3. Insert Customers
INSERT INTO customers (customer_id, customer_name, region_id, customer_segment, created_at) VALUES
(1, 'EuroTech GmbH', 1, 'Enterprise', '2024-01-15'),
(2, 'Paris Retail Group', 2, 'Mid-Market', '2024-02-10'),
(3, 'London Systems Ltd', 3, 'Enterprise', '2024-03-05'),
(4, 'Chennai Digital Pvt Ltd', 4, 'Enterprise', '2024-03-20'),
(5, 'Tokyo Smart Corp', 5, 'Strategic', '2024-04-12'),
(6, 'Austin Commerce Inc', 6, 'Enterprise', '2024-05-18'),
(7, 'Toronto Data Corp', 7, 'Mid-Market', '2024-06-01');

ALTER SEQUENCE customers_customer_id_seq RESTART WITH 8;

-- 4. Insert Products
INSERT INTO products (product_id, product_name, category, subcategory, unit_price) VALUES
(1, 'Analytics Platform', 'Analytics', 'Core Software', 15000.00),
(2, 'AI Assistant', 'AI & ML', 'Copilots', 12000.00),
(3, 'Data Warehouse License', 'Data Infrastructure', 'Storage & Compute', 25000.00),
(4, 'BI Dashboard Pro', 'Visualization', 'Reporting Tools', 8000.00),
(5, 'Consulting Package', 'Professional Services', 'Advisory', 18000.00),
(6, 'Data Engineering Package', 'Professional Services', 'Implementation', 22000.00);

ALTER SEQUENCE products_product_id_seq RESTART WITH 7;

-- 5. Insert Orders & Order Items across Q3 2025, Q4 2025, Q1 2026, Q2 2026
-- We generate 36 realistic enterprise transactions with varied pricing, discounts, and cost shifts.
-- Notice: In Q2 2026 for European orders (regions 1, 2, 3), unit_cost is noticeably higher due to logistics & material costs,
-- creating the real historical margin decline from 31.4% to 27.2%!

INSERT INTO orders (order_id, order_date, customer_id, region_id, order_status, currency) VALUES
-- Q3 2025
(1001, '2025-07-15', 1, 1, 'Completed', 'USD'),
(1002, '2025-07-28', 4, 4, 'Completed', 'USD'),
(1003, '2025-08-10', 6, 6, 'Completed', 'USD'),
(1004, '2025-08-22', 2, 2, 'Completed', 'USD'),
(1005, '2025-09-05', 5, 5, 'Completed', 'USD'),
(1006, '2025-09-19', 3, 3, 'Completed', 'USD'),
(1007, '2025-09-29', 7, 7, 'Completed', 'USD'),

-- Q4 2025
(1008, '2025-10-12', 1, 1, 'Completed', 'USD'),
(1009, '2025-10-25', 6, 6, 'Completed', 'USD'),
(1010, '2025-11-04', 4, 4, 'Completed', 'USD'),
(1011, '2025-11-18', 5, 5, 'Completed', 'USD'),
(1012, '2025-12-02', 3, 3, 'Completed', 'USD'),
(1013, '2025-12-15', 2, 2, 'Completed', 'USD'),
(1014, '2025-12-28', 7, 7, 'Completed', 'USD'),

-- Q1 2026 (Baseline: Europe Gross Margin ~31.4%)
(1015, '2026-01-10', 1, 1, 'Completed', 'USD'),
(1016, '2026-01-22', 2, 2, 'Completed', 'USD'),
(1017, '2026-02-05', 3, 3, 'Completed', 'USD'),
(1018, '2026-02-18', 4, 4, 'Completed', 'USD'),
(1019, '2026-03-01', 5, 5, 'Completed', 'USD'),
(1020, '2026-03-14', 6, 6, 'Completed', 'USD'),
(1021, '2026-03-25', 7, 7, 'Completed', 'USD'),
(1022, '2026-03-29', 1, 1, 'Completed', 'USD'),

-- Q2 2026 (Europe Gross Margin drops to 27.2% due to elevated unit costs)
(1023, '2026-04-05', 1, 1, 'Completed', 'USD'),
(1024, '2026-04-14', 2, 2, 'Completed', 'USD'),
(1025, '2026-04-26', 3, 3, 'Completed', 'USD'),
(1026, '2026-05-03', 4, 4, 'Completed', 'USD'),
(1027, '2026-05-12', 5, 5, 'Completed', 'USD'),
(1028, '2026-05-20', 6, 6, 'Completed', 'USD'),
(1029, '2026-05-28', 7, 7, 'Completed', 'USD'),
(1030, '2026-06-04', 1, 1, 'Completed', 'USD'),
(1031, '2026-06-11', 2, 2, 'Completed', 'USD'),
(1032, '2026-06-18', 3, 3, 'Completed', 'USD'),
(1033, '2026-06-22', 4, 4, 'Completed', 'USD'),
(1034, '2026-06-25', 6, 6, 'Completed', 'USD'),
(1035, '2026-06-28', 5, 5, 'Completed', 'USD'),
(1036, '2026-06-30', 2, 2, 'Pending',   'USD'); -- Will be excluded by semantic_sales view

ALTER SEQUENCE orders_order_id_seq RESTART WITH 1037;

-- 6. Insert Order Items
INSERT INTO order_items (order_id, product_id, quantity, unit_price, unit_cost, discount) VALUES
-- Q3 2025
(1001, 1, 5, 15000.00, 10200.00, 5.0),
(1001, 5, 2, 18000.00, 12600.00, 0.0),
(1002, 3, 3, 25000.00, 15500.00, 8.0),
(1003, 2, 6, 12000.00, 7800.00, 4.0),
(1004, 4, 8, 8000.00, 5600.00, 10.0),
(1005, 1, 4, 15000.00, 10500.00, 2.0),
(1006, 6, 2, 22000.00, 15000.00, 5.0),
(1007, 2, 3, 12000.00, 8100.00, 0.0),

-- Q4 2025
(1008, 1, 6, 15000.00, 10300.00, 4.0),
(1008, 3, 2, 25000.00, 17000.00, 6.0),
(1009, 2, 8, 12000.00, 7900.00, 5.0),
(1010, 3, 4, 25000.00, 15200.00, 5.0),
(1011, 4, 10, 8000.00, 5400.00, 7.0),
(1012, 5, 3, 18000.00, 12200.00, 0.0),
(1013, 1, 4, 15000.00, 10400.00, 3.0),
(1014, 6, 3, 22000.00, 14800.00, 5.0),

-- Q1 2026 (Europe standard unit_cost ~68-69% of price -> 31.4% margin)
(1015, 1, 8, 15000.00, 10250.00, 3.0),
(1015, 2, 4, 12000.00, 8200.00, 0.0),
(1016, 4, 12, 8000.00, 5500.00, 5.0),
(1017, 3, 3, 25000.00, 17100.00, 4.0),
(1018, 1, 6, 15000.00, 9300.00, 2.0),
(1018, 3, 4, 25000.00, 15000.00, 5.0),
(1019, 2, 7, 12000.00, 8000.00, 3.0),
(1020, 3, 5, 25000.00, 16500.00, 6.0),
(1021, 6, 3, 22000.00, 14800.00, 4.0),
(1022, 5, 4, 18000.00, 12300.00, 0.0),

-- Q2 2026 (Europe logistics surge & supply costs drive unit_cost up to 72.8% of price -> 27.2% margin!)
(1023, 1, 9, 15000.00, 11050.00, 4.0),
(1023, 3, 3, 25000.00, 18400.00, 5.0),
(1024, 4, 14, 8000.00, 5950.00, 6.0),
(1025, 2, 6, 12000.00, 8900.00, 3.0),
(1025, 6, 2, 22000.00, 16400.00, 0.0),
(1026, 1, 8, 15000.00, 9100.00, 2.0),
(1026, 3, 5, 25000.00, 15100.00, 4.0),
(1027, 2, 8, 12000.00, 7900.00, 4.0),
(1028, 3, 6, 25000.00, 16200.00, 5.0),
(1029, 5, 3, 18000.00, 12000.00, 2.0),
(1030, 1, 7, 15000.00, 11100.00, 5.0),
(1031, 2, 5, 12000.00, 8950.00, 2.0),
(1032, 5, 4, 18000.00, 13300.00, 0.0),
(1033, 6, 4, 22000.00, 13400.00, 3.0),
(1034, 1, 6, 15000.00, 9800.00, 2.0),
(1035, 4, 10, 8000.00, 5300.00, 4.0),
(1036, 1, 2, 15000.00, 10500.00, 0.0); -- In completed order, excluded from semantic_sales

-- 7. Insert Initial Query Audit Log Samples
INSERT INTO query_audit_logs (user_question, generated_sql, metric_used, dimensions_used, execution_status, execution_time_ms, row_count, ai_confidence, validation_result) VALUES
(
    'Why did European margins drop last quarter?',
    'SELECT country, ROUND(SUM(revenue), 2) AS revenue, ROUND(SUM(cost), 2) AS cost, ROUND(((SUM(revenue) - SUM(cost)) * 1.0 / NULLIF(SUM(revenue), 0)) * 100.0, 2) AS margin FROM semantic_sales WHERE continent = ''Europe'' GROUP BY country ORDER BY margin ASC;',
    'margin',
    ARRAY['country', 'continent'],
    'SUCCESS',
    28.40,
    3,
    0.98,
    'PASSED_READ_ONLY_SEMANTIC'
),
(
    'What is our total revenue?',
    'SELECT ROUND(SUM(revenue), 2) AS total_revenue FROM semantic_sales;',
    'revenue',
    ARRAY[]::TEXT[],
    'SUCCESS',
    12.10,
    1,
    0.99,
    'PASSED_READ_ONLY_SEMANTIC'
);
