"use client";

import React, { useState } from "react";
import { ShieldCheck, Check, Copy, Hash, Terminal, FileCode, CheckCircle2 } from "lucide-react";

interface AuditTrailProps {
  questionOrKpi?: string;
  value: string;
  version: string;
  queryId: string;
  snapshotId: string;
  executedDate: string;
  source: string;
  fingerprint: string;
}

export const AuditTrail: React.FC<AuditTrailProps> = ({
  questionOrKpi = "Gross Margin",
  value = "27.2%",
  version = "v2.1",
  queryId = "QRY-83921",
  snapshotId = "SNAP-2026-Q3-EU-001",
  executedDate = "30 Sep 2026",
  source = "Cube Semantic Layer (Sales.yml)",
  fingerprint = "MM-GM-V21-Q3-EU-7A82F"
}) => {
  const [copiedFingerprint, setCopiedFingerprint] = useState(false);

  const handleCopyFingerprint = () => {
    navigator.clipboard.writeText(fingerprint);
    setCopiedFingerprint(true);
    setTimeout(() => setCopiedFingerprint(false), 2000);
  };

  const auditItems = [
    { label: "Question / KPI", value: questionOrKpi, highlight: true },
    { label: "Governed Value", value: value, highlight: true, fontMono: true },
    { label: "Metric Version", value: version, fontMono: true },
    { label: "Semantic Query ID", value: queryId, fontMono: true },
    { label: "Data Snapshot ID", value: snapshotId, fontMono: true },
    { label: "Executed Timestamp", value: executedDate },
    { label: "Execution Status", value: "Verified", badge: "verified" },
    { label: "Data Source", value: source },
    { label: "SQL Generated By LLM", value: "NONE", badge: "none" },
    { label: "Semantic Validation", value: "PASSED", badge: "passed" },
    { label: "Calculation Validation", value: "PASSED", badge: "passed" }
  ];

  return (
    <div className="p-5 rounded-2xl bg-slate-900/90 border border-slate-800/90 shadow-xl space-y-4">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-800/80 pb-3">
        <div className="flex items-center gap-2">
          <ShieldCheck className="w-4 h-4 text-emerald-400" />
          <h3 className="text-xs font-bold text-slate-200 uppercase tracking-wider">
            GOVERNANCE AUDIT TRAIL
          </h3>
        </div>
        <span className="text-[10px] font-mono text-emerald-300 bg-emerald-500/10 px-2 py-0.5 rounded border border-emerald-500/20 font-bold">
          100% Deterministic Compliance
        </span>
      </div>

      {/* Number Hash / Calculation Fingerprint (Section 18) */}
      <div className="p-3.5 rounded-xl bg-slate-950/80 border border-sky-500/30 flex flex-wrap items-center justify-between gap-3">
        <div className="space-y-0.5">
          <div className="flex items-center gap-1.5 text-[10px] uppercase font-bold text-sky-400 tracking-wider">
            <Hash className="w-3.5 h-3.5" />
            <span>Calculation Fingerprint (Number Hash)</span>
          </div>
          <span className="text-sm sm:text-base font-black text-slate-100 font-mono tracking-wider">
            {fingerprint}
          </span>
          <p className="text-[10px] text-slate-400">
            Immutable audit identifier binding Metric Version + Semantic Query + Filters + Snapshot + Calculation.
          </p>
        </div>

        <button
          onClick={handleCopyFingerprint}
          className="flex items-center gap-1 px-3 py-1.5 rounded-lg bg-sky-500/10 hover:bg-sky-500/20 text-sky-300 border border-sky-500/30 text-xs font-medium transition-all shrink-0"
        >
          {copiedFingerprint ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
          <span>{copiedFingerprint ? "Copied Fingerprint" : "Copy Hash"}</span>
        </button>
      </div>

      {/* Audit Matrix Table */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs">
        {auditItems.map((item, idx) => (
          <div
            key={idx}
            className="p-2.5 rounded-xl bg-slate-950/60 border border-slate-800/80 flex items-center justify-between gap-2"
          >
            <span className="text-[11px] text-slate-400">{item.label}:</span>
            <div className="text-right">
              {item.badge === "none" ? (
                <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-emerald-500/15 text-emerald-300 border border-emerald-500/30 font-black">
                  NONE (Zero Hallucination)
                </span>
              ) : item.badge === "passed" || item.badge === "verified" ? (
                <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 font-bold flex items-center gap-1">
                  <CheckCircle2 className="w-3 h-3" />
                  {item.value}
                </span>
              ) : (
                <span
                  className={`font-semibold text-slate-200 ${
                    item.fontMono ? "font-mono" : ""
                  } ${item.highlight ? "text-sky-300" : ""}`}
                >
                  {item.value}
                </span>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
