"use client";

import React from "react";
import { X, Shield, FileText, HelpCircle, CheckCircle2 } from "lucide-react";

interface TermsPrivacyHelpModalProps {
  type: "privacy" | "terms" | "help" | null;
  onClose: () => void;
}

export const TermsPrivacyHelpModal: React.FC<TermsPrivacyHelpModalProps> = ({ type, onClose }) => {
  if (!type) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md animate-in fade-in duration-200">
      <div
        className="w-full max-w-lg rounded-2xl bg-slate-900 border border-slate-800 p-6 shadow-2xl space-y-4 relative max-h-[85vh] flex flex-col"
        role="dialog"
        aria-modal="true"
      >
        <button
          onClick={onClose}
          className="absolute top-4 right-4 p-1.5 rounded-lg text-slate-400 hover:text-slate-200 hover:bg-slate-800 transition-colors"
          aria-label="Close dialog"
        >
          <X className="w-4 h-4" />
        </button>

        <div className="flex items-center gap-3 border-b border-slate-800 pb-3">
          <div className="w-9 h-9 rounded-xl bg-slate-800 flex items-center justify-center text-sky-400">
            {type === "privacy" && <Shield className="w-5 h-5" />}
            {type === "terms" && <FileText className="w-5 h-5" />}
            {type === "help" && <HelpCircle className="w-5 h-5" />}
          </div>
          <div>
            <h3 className="text-base font-bold text-slate-100 capitalize">
              {type === "privacy" && "Enterprise Privacy Policy"}
              {type === "terms" && "Terms of Service"}
              {type === "help" && "MetricMind Help & Support"}
            </h3>
            <p className="text-xs text-slate-400">
              MetricMind Agentic Semantic BI Engine • Version 1.0.0
            </p>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto space-y-3 text-xs text-slate-300 pr-1 custom-scrollbar">
          {type === "privacy" && (
            <>
              <p>
                At MetricMind, data privacy and semantic governance are foundational. We implement
                zero-trust data isolation ensuring your business data stays governed and protected.
              </p>
              <h4 className="font-semibold text-slate-200 pt-1">1. Zero Direct SQL Exposure</h4>
              <p className="text-slate-400">
                All data queries execute against governed semantic metrics (Cube/dbt models). Raw database
                tables and schemas are never directly exposed to LLM endpoints.
              </p>
              <h4 className="font-semibold text-slate-200 pt-1">2. No AI Training on Customer Data</h4>
              <p className="text-slate-400">
                Customer analytical questions and aggregated responses are never used to train foundational AI
                models. All reasoning occurs in isolated tenant sessions.
              </p>
              <h4 className="font-semibold text-slate-200 pt-1">3. Role-Based Data Masking</h4>
              <p className="text-slate-400">
                Access tokens and user roles strictly constrain dimension visibility. Column-level and row-level
                security policies are enforced on every analytical payload.
              </p>
            </>
          )}

          {type === "terms" && (
            <>
              <p>
                By signing in to MetricMind Enterprise, you agree to comply with your corporate IT
                governance standards and MetricMind semantic data policies.
              </p>
              <h4 className="font-semibold text-slate-200 pt-1">1. Authorized Corporate Use</h4>
              <p className="text-slate-400">
                MetricMind is licensed exclusively for authorized enterprise analytics, business intelligence,
                and governed decision making.
              </p>
              <h4 className="font-semibold text-slate-200 pt-1">2. Deterministic Verification</h4>
              <p className="text-slate-400">
                All metric figures generated by the MetricMind agent include cryptographic governance signatures
                and lineage references verified by departmental metric owners.
              </p>
            </>
          )}

          {type === "help" && (
            <>
              <p>
                Need assistance navigating MetricMind or configuring your enterprise session?
              </p>
              <div className="space-y-2 pt-2">
                <div className="p-3 rounded-xl bg-slate-950/60 border border-slate-800 space-y-1">
                  <span className="font-semibold text-sky-400 text-xs">Demo Mode Inquiries</span>
                  <p className="text-[11px] text-slate-400">
                    Click <strong>Continue in Demo Mode</strong> on the login screen to explore the full suite with
                    pre-populated enterprise data (Rajesh Kapoor, Executive).
                  </p>
                </div>
                <div className="p-3 rounded-xl bg-slate-950/60 border border-slate-800 space-y-1">
                  <span className="font-semibold text-emerald-400 text-xs">Credential Reset</span>
                  <p className="text-[11px] text-slate-400">
                    Use the <strong>Forgot password?</strong> page to request a recovery link for your registered
                    corporate email address.
                  </p>
                </div>
                <div className="p-3 rounded-xl bg-slate-950/60 border border-slate-800 space-y-1">
                  <span className="font-semibold text-indigo-400 text-xs">Support Contact</span>
                  <p className="text-[11px] text-slate-400">
                    Contact your enterprise internal BI administrator or email <code>support@metricmind.app</code>.
                  </p>
                </div>
              </div>
            </>
          )}
        </div>

        <div className="pt-2 border-t border-slate-800 flex justify-end">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
