import {
  SemanticQueryPayload,
  APPROVED_MEASURES,
  APPROVED_DIMENSIONS
} from "../semanticSchema";
import { buildCubeRestPayload, executeCubeQuery, CubeNormalizedResponse } from "../cubeClient";
import { ApiCallInfo, SqlExecutionInfo } from "@/types";

export interface CubeExecutionEnvelope {
  normalizedResponse: CubeNormalizedResponse;
  apiCallInfo: ApiCallInfo;
  sqlInfo: SqlExecutionInfo;
  fromCache?: boolean;
}

/**
 * Maps short dimension or measure names to Cube.dev member identifiers
 */
function toCubeMember(name: string, type: "measure" | "dimension"): string {
  if (name.includes(".")) return name;
  if (type === "measure") {
    return `Sales.${name}`;
  }
  const foundDim = APPROVED_DIMENSIONS.find((d) => d.name === name);
  const cubeName = foundDim ? foundDim.cube : "Geography";
  return `${cubeName}.${name}`;
}

/**
 * Sanitizes Cube REST query payload to ensure zero credentials, tokens, or auth headers are exposed.
 */
export function sanitizeCubePayload(payload: any): any {
  if (!payload) return {};
  const clone = JSON.parse(JSON.stringify(payload));
  // Strip any header or secret fields if present
  delete clone.authorization;
  delete clone.token;
  delete clone.secret;
  delete clone.apiKey;
  return clone;
}

/**
 * Executes a semantic query via the Cube REST adapter and collects transparency metadata.
 */
export async function executeGovernedCubeQuery(
  semanticJson: SemanticQueryPayload,
  options?: { isDryRun?: boolean }
): Promise<CubeExecutionEnvelope> {
  const startTime = performance.now();
  const cubePayload = buildCubeRestPayload(semanticJson);
  const sanitizedPayload = sanitizeCubePayload(cubePayload);

  // Execute query via cubeClient
  const normalizedResponse = await executeCubeQuery(semanticJson);
  const durationMs = Math.round(performance.now() - startTime);

  // Check if live Cube provided genuine SQL
  let genuineSql: string | null = null;
  const rawCube = normalizedResponse.metadata.raw_cube_response;
  if (rawCube && rawCube.sql) {
    if (typeof rawCube.sql === "string") {
      genuineSql = rawCube.sql;
    } else if (rawCube.sql.sql) {
      genuineSql = rawCube.sql.sql;
    }
  }

  const sqlAvailable = Boolean(genuineSql);
  const sqlInfo: SqlExecutionInfo = {
    source: "Cube Semantic Layer",
    sql_generated_by_llm: "NONE",
    sql: genuineSql,
    available: sqlAvailable,
    message: sqlAvailable
      ? "SQL generated and executed exclusively by the Cube Semantic Layer (0% generated by AI)."
      : "SQL preview is unavailable for this semantic query. The request was executed through the Cube Semantic Layer."
  };

  const apiCallInfo: ApiCallInfo = {
    endpoint: "POST /cubejs-api/v1/load",
    method: "POST",
    payload: sanitizedPayload,
    status_code: normalizedResponse.success ? 200 : 400,
    execution_time_ms: durationMs,
    result_rows: normalizedResponse.data?.length || 0,
    sanitized: true
  };

  return {
    normalizedResponse,
    apiCallInfo,
    sqlInfo
  };
}
